type Action @aws_api_key @aws_iam {
  Accepted: Boolean
  ActionItem: String
  ActionStatus: Status
  Conversations: ModelConversationConnection
  Delegate: Boolean
  Due_date: AWSDateTime
  Encrypt: Boolean
  GuardRails: AWSJSON
  History: AWSJSON
  Ignore: Boolean
  FileUrls: [String]
  KBLink: [String]
  Notes: [String]
  Notify: String
  orderRank: Int
  Owner: String
  Type: String
  _deleted: Boolean
  _lastChangedAt: AWSTimestamp
  _version: Int
  actionlistID: ID!
  createdAt: AWSDateTime!
  id: ID!
  isImportant: Boolean
  isUrgent: Boolean
  knowledgeBaseID: ID
  prompt: String
  tags: [String]
  updatedAt: AWSDateTime!
  userLike: Int
  assignedUserInfo: ActionListTransferUserInfo
  assignedByUserInfo: ActionListTransferUserInfo
}

type ActionList @aws_api_key @aws_iam {
  Context: String
  Delegate: Boolean
  DueDate: AWSDateTime
  Ignore: Boolean
  Tags: [String]
  orderRank: Int
  _deleted: Boolean
  _lastChangedAt: AWSTimestamp
  _version: Int
  action: String
  actionItems: ModelActionConnection
  actionListStatus: Status
  actionboardID: ID
  createdAt: AWSDateTime!
  id: ID!
  isImportant: Boolean
  isUrgent: Boolean
  knowledgeBaseID: ID
  notes: String
  savedBy: String
  updatedAt: AWSDateTime!
  metadata: ActionListMetaData
  transferInfo: TransferInfo
  assignedUserInfo: ActionListTransferUserInfo
  assignedByUserInfo: ActionListTransferUserInfo
}

type ActionListMetaData {
  mainBoardId: ID
  newBoardId: ID
}

type ActionListTransferUserInfo {
  id: ID!
  name: String
  email: String!
  avatar: String
}

type TransferInfo {
  transferStatus: TransferStatus
  transferRequestByUserInfo: ActionListTransferUserInfo
  transferAcceptByUserInfo: ActionListTransferUserInfo
  transferRejectByUserInfo: ActionListTransferUserInfo
  transferRequestTime: AWSDateTime
  transferAcceptTime: AWSDateTime
  transferRejectTime: AWSDateTime
}

enum ActionListOrItemType {
  ACTION_LIST
  ACTION_ITEM
}

enum TransferStatus {
  REQUESTED
  ACCEPTED
  REJECTED
}

/*============================================================
Queries
============================================================*/
 
getAction(id: ID!): Action
getAction_test(id: ID!): Action
getActionByActionlistID_test(actionlistID: ID!): [Action]
actionsByActionlistID(
		actionlistID: ID!,
		filter: ModelActionFilterInput,
		limit: Int,
		nextToken: String,
		sortDirection: ModelSortDirection
	): ModelActionConnection
actionsByKnowledgeBaseID(
		filter: ModelActionFilterInput,
		knowledgeBaseID: ID!,
		limit: Int,
		nextToken: String,
		sortDirection: ModelSortDirection
	): ModelActionConnection
    listActions(filter: ModelActionFilterInput, limit: Int, nextToken: String): ModelActionConnection

    	syncActions(
		filter: ModelActionFilterInput,
		lastSync: AWSTimestamp,
		limit: Int,
		nextToken: String
	): ModelActionConnection